project:
  type: website

website:
  title: "IS415-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1"
            href: In-class_Ex/In-class_Ex01/In-class_Ex01.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      
  sidebar:
    style: docked
    search: true
    contents:
      - text: The Building Block
        href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
        contents: 
          - text: Geospatial Data Science with R
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01_chap01.qmd
          - text: Thematic Mapping and GeoVisualisation with R
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01_chap02.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

