project:
  type: website

website:
  title: "IS415-VAA"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "The Building Block"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex_LearningObj.html
          - text: "Hands-on Exercise 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01_chap01.html
          - text: "Hands-on Exercise 2"
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02_chap02.html
      - text: "In-class Exercises"
        menu: 
          - text: "In-class Exercise 1"
            href: In-class_Ex/In-class_Ex01/In-class_Ex01.html
      - text: "Take-home Exercises"
        menu:
          - text: "Take-home Exercise 1"
            href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html
          - text: "Take-home Exercise 2"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      
  sidebar:
    - title: "Hands-on Exercise"
      style: docked
      contents:
        - text: The Building Block
          href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex_LearningObj.qmd
          contents: 
            - text: Geospatial Data Science with R
              href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01_chap01.qmd
            - text: Thematic Mapping and GeoVisualisation with R
              href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02_chap02.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

